name = "digibazaar24-income-boost"
compatibility_date = "2024-05-07"

[build]
command = "npm run build"
cwd = "."

[site]
bucket = ".svelte-kit/cloudflare"
entry-point = "workers-site"

[build.upload]
format = "service-worker"
